chrony:
  config: /etc/chrony.conf
  svc_name: chronyd
  pkg_name: chrony
  optional: 
    driftfile: /var/lib/chrony/drift
    ntsdumpdir: /var/lib/chrony
    makestep: 1.0 3
    maxupdateskew: 100.0
    keyfile: /etc/chrony.keys
    logdir: /var/log/chrony
    leapsectz: right/UTC
    rtcsync: ''
  ntp_servers: 
    - 'ntp1.aliyun.com'
    - 'ntp2.aliyun.com'
    - 'ntp3.aliyun.com'
    - 'ntp4.aliyun.com'
    - 'ntp5.aliyun.com'
    - 'ntp6.aliyun.com'
    - 'ntp7.aliyun.com'