chrony:
  config: /etc/chrony.conf
  svc_name: chronyd
  pkg_name: chrony
  optional: 
    stratumweight: 0.05
    driftfile: /var/lib/chrony/drift
    makestep: 1.0 3
    bindcmdaddress: 127.0.0.1
    logchange: 0.5
    logdir: /var/log/chrony
  ntp_servers: 
    - 'ntp1.aliyun.com'
    - 'ntp2.aliyun.com'
    - 'ntp3.aliyun.com'
    - 'ntp4.aliyun.com'
    - 'ntp5.aliyun.com'
    - 'ntp6.aliyun.com'
    - 'ntp7.aliyun.com'
