chrony:
  config: /etc/chrony.conf
  svc_name: chronyd
  pkg_name: chrony
  optional: 
    keyfile: /etc/chrony/chrony.keys
    logdir: /var/log/chrony
    driftfile: /var/lib/chrony/chrony.drift
  ntp_servers: 
    - 'ntp1.aliyun.com'
    - 'ntp2.aliyun.com'
    - 'ntp3.aliyun.com'
    - 'ntp4.aliyun.com'
    - 'ntp5.aliyun.com'
    - 'ntp6.aliyun.com'
    - 'ntp7.aliyun.com'