---
# tasks file for flannel
- block:
    - name: Create flannel data directory
      file: 
        name: '{{ kubernetes.addon.location }}/flannel'
        state: directory
        mode: '0755'

    - name: Stat flannel yaml file
      stat: 
        path: '{{ kubernetes.addon.location }}/flannel/flannel.yaml'
      register: flannel_yaml_file
      run_once: true

    - name: Clean old deployment
      shell: 'kubectl delete -f {{ kubernetes.addon.location }}/flannel/flannel.yaml'
      run_once: true
      when: flannel_yaml_file.stat.exists

    - name: Waiting deployment delete
      shell: kubectl get po -n kube-system
      register: waiting_for_delete_deployment_done
      until: waiting_for_delete_deployment_done.rc == 0 and waiting_for_delete_deployment_done.stdout.find("kube-flannel") == -1
      retries: 15
      delay: 5
      changed_when: false
      when: flannel_yaml_file.stat.exists
      run_once: true

    - name: Deployment flannel --- part.1
      template: 
        src: flannel.yaml.j2
        dest: '{{ kubernetes.addon.location }}/flannel/flannel.yaml'

    - name: Deployment flannel --- part.2
      shell: 'kubectl apply -f {{ kubernetes.addon.location }}/flannel/flannel.yaml'
      run_once: true
  when: kubernetes.network == "flannel"