---
# defaults file for ipvs
ipvs:
  filename: /etc/modules
  params:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh

    # - ip_vs
    # - ip_vs_lc
    # - ip_vs_wlc
    # - ip_vs_rr
    # - ip_vs_wrr
    # - ip_vs_lblc
    # - ip_vs_lblcr
    # - ip_vs_dh
    # - ip_vs_sh
    # - ip_vs_fo
    # - ip_vs_nq
    # - ip_vs_sed
    # - ip_vs_ftp