- name: Create calico data directory
  file: 
    name: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - '{{ kubernetes.addon.location }}/calico'
  run_once: true
  when: inventory_hostname in groups['master']

- name: Deployment calico --- part.1
  template: 
    src: '{{ item.src }}'
    dest: '{{ kubernetes.addon.location }}/{{ item.dest }}'
  with_items:
    - { src: 'calico/rbac-kdd.yaml.j2', dest: 'calico/rbac-kdd.yaml' }
    - { src: 'calico/calico.yaml.j2', dest: 'calico/calico.yaml' }
  run_once: true
  when: inventory_hostname in groups['master']

- name: Deployment calico --- part.2
  command: 'kubectl apply -f {{ kubernetes.addon.location }}/{{ item }}'
  with_items:
    - calico/rbac-kdd.yaml
    - calico/calico.yaml
  run_once: true
  when: inventory_hostname in groups['master']