- name: Create canal data directory
  file: 
    name: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - '{{ kubernetes.addon.location }}/canal'
  run_once: true
  when: inventory_hostname in groups['master']

- name: Deployment canal --- part.1
  template: 
    src: '{{ item.src }}'
    dest: '{{ kubernetes.addon.location }}/{{ item.dest }}'
  with_items:
    - { src: 'canal/rbac.yaml.j2', dest: 'canal/rbac.yaml' }
    - { src: 'canal/canal.yaml.j2', dest: 'canal/canal.yaml' }
  run_once: true
  when: inventory_hostname in groups['master']

- name: Deployment canal --- part.2
  command: 'kubectl apply -f {{ kubernetes.addon.location }}/{{ item }}'
  with_items:
    - canal/rbac.yaml
    - canal/canal.yaml
  run_once: true
  when: inventory_hostname in groups['master']