- name: Create coredns data directory
  file: 
    name: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - '{{ kubernetes.addon.location }}/coredns'
  run_once: true
  when: inventory_hostname in groups['kube-master']

- name: Deployment coredns --- part.1
  template: 
    src: '{{ item.src }}'
    dest: '{{ kubernetes.addon.location }}/{{ item.dest }}'
  with_items:
    - { src: 'coredns/coredns.yaml.j2', dest: 'coredns/coredns.yaml' }
  run_once: true
  when: inventory_hostname in groups['kube-master']

- name: Deployment coredns --- part.2
  command: 'kubectl apply -f {{ kubernetes.addon.location }}/{{ item }}'
  with_items:
    - coredns/coredns.yaml
  run_once: true
  when: inventory_hostname in groups['kube-master']