svc_name: firewalld

package:
  - conntrack
  - net-tools
  - sysstat
  - unzip
  - tcpdump
  - telnet
  - lsof
  - strace
  - wget
  - psmisc
  - ipset
  - socat
  - bash-completion
  - nfs-utils
  - bind-utils